"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.struct_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _SpaceType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SpaceTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SpaceType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BOX: _SpaceType.ValueType  # 0
    """连续空间 (gym.spaces.Box) - shape=[dims], 每维有low/high"""
    DISCRETE: _SpaceType.ValueType  # 1
    """离散空间 (gym.spaces.Discrete) - shape=[], high=[n-1]表示n个动作"""
    MULTI_DISCRETE: _SpaceType.ValueType  # 2
    """如果discrete_values非空，则动作值来自该列表
    多离散空间 - shape=[groups], high=[n1-1,n2-1,...]每组动作数
    """
    MULTI_BINARY: _SpaceType.ValueType  # 3
    """多二进制空间 - shape=[bits], low/high全为[0]/[1]"""
    DISCRETE_FLOAT: _SpaceType.ValueType  # 4
    """离散浮点空间 - 预定义的浮点值列表，使用discrete_values字段"""

class SpaceType(_SpaceType, metaclass=_SpaceTypeEnumTypeWrapper): ...

BOX: SpaceType.ValueType  # 0
"""连续空间 (gym.spaces.Box) - shape=[dims], 每维有low/high"""
DISCRETE: SpaceType.ValueType  # 1
"""离散空间 (gym.spaces.Discrete) - shape=[], high=[n-1]表示n个动作"""
MULTI_DISCRETE: SpaceType.ValueType  # 2
"""如果discrete_values非空，则动作值来自该列表
多离散空间 - shape=[groups], high=[n1-1,n2-1,...]每组动作数
"""
MULTI_BINARY: SpaceType.ValueType  # 3
"""多二进制空间 - shape=[bits], low/high全为[0]/[1]"""
DISCRETE_FLOAT: SpaceType.ValueType  # 4
"""离散浮点空间 - 预定义的浮点值列表，使用discrete_values字段"""
Global___SpaceType: typing_extensions.TypeAlias = SpaceType

@typing.final
class GetInfoRequest(google.protobuf.message.Message):
    """基础消息类型"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetInfoRequest: typing_extensions.TypeAlias = GetInfoRequest

@typing.final
class GetInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SCENARIOS_FIELD_NUMBER: builtins.int
    ENV_IDS_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    version: builtins.str
    name: builtins.str
    @property
    def scenarios(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def env_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def info(self) -> google.protobuf.struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        scenarios: collections.abc.Iterable[builtins.str] | None = ...,
        env_ids: collections.abc.Iterable[builtins.str] | None = ...,
        info: google.protobuf.struct_pb2.Struct | None = ...,
        version: builtins.str = ...,
        name: builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["info", b"info"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["env_ids", b"env_ids", "info", b"info", "name", b"name", "scenarios", b"scenarios", "version", b"version"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetInfoResponse: typing_extensions.TypeAlias = GetInfoResponse

@typing.final
class CreateEnvironmentRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENV_ID_FIELD_NUMBER: builtins.int
    SCENARIO_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    env_id: builtins.str
    scenario: builtins.str
    @property
    def config(self) -> google.protobuf.struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        env_id: builtins.str = ...,
        scenario: builtins.str = ...,
        config: google.protobuf.struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["config", b"config"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["config", b"config", "env_id", b"env_id", "scenario", b"scenario"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateEnvironmentRequest: typing_extensions.TypeAlias = CreateEnvironmentRequest

@typing.final
class CreateEnvironmentResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["message", b"message", "success", b"success"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateEnvironmentResponse: typing_extensions.TypeAlias = CreateEnvironmentResponse

@typing.final
class ResetEnvironmentRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENV_ID_FIELD_NUMBER: builtins.int
    env_id: builtins.str
    def __init__(
        self,
        *,
        env_id: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["env_id", b"env_id"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResetEnvironmentRequest: typing_extensions.TypeAlias = ResetEnvironmentRequest

@typing.final
class ResetEnvironmentResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBSERVATIONS_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    @property
    def observations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Observation]: ...
    @property
    def info(self) -> google.protobuf.struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        observations: collections.abc.Iterable[Global___Observation] | None = ...,
        info: google.protobuf.struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["info", b"info"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["info", b"info", "observations", b"observations"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResetEnvironmentResponse: typing_extensions.TypeAlias = ResetEnvironmentResponse

@typing.final
class StepEnvironmentRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENV_ID_FIELD_NUMBER: builtins.int
    ACTIONS_FIELD_NUMBER: builtins.int
    env_id: builtins.str
    @property
    def actions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Action]: ...
    def __init__(
        self,
        *,
        env_id: builtins.str = ...,
        actions: collections.abc.Iterable[Global___Action] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["actions", b"actions", "env_id", b"env_id"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StepEnvironmentRequest: typing_extensions.TypeAlias = StepEnvironmentRequest

@typing.final
class StepEnvironmentResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBSERVATIONS_FIELD_NUMBER: builtins.int
    REWARDS_FIELD_NUMBER: builtins.int
    DONE_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    @property
    def observations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Observation]: ...
    @property
    def rewards(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def done(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bool]: ...
    @property
    def info(self) -> google.protobuf.struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        observations: collections.abc.Iterable[Global___Observation] | None = ...,
        rewards: collections.abc.Iterable[builtins.float] | None = ...,
        done: collections.abc.Iterable[builtins.bool] | None = ...,
        info: google.protobuf.struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["info", b"info"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["done", b"done", "info", b"info", "observations", b"observations", "rewards", b"rewards"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StepEnvironmentResponse: typing_extensions.TypeAlias = StepEnvironmentResponse

@typing.final
class CloseEnvironmentRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENV_ID_FIELD_NUMBER: builtins.int
    env_id: builtins.str
    def __init__(
        self,
        *,
        env_id: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["env_id", b"env_id"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CloseEnvironmentRequest: typing_extensions.TypeAlias = CloseEnvironmentRequest

@typing.final
class CloseEnvironmentResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["message", b"message", "success", b"success"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CloseEnvironmentResponse: typing_extensions.TypeAlias = CloseEnvironmentResponse

@typing.final
class Observation(google.protobuf.message.Message):
    """数据类型定义"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def metadata(self) -> google.protobuf.struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        data: collections.abc.Iterable[builtins.float] | None = ...,
        metadata: google.protobuf.struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["metadata", b"metadata"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["data", b"data", "metadata", b"metadata"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Observation: typing_extensions.TypeAlias = Observation

@typing.final
class Action(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FLOAT_VALUE_FIELD_NUMBER: builtins.int
    INT_VALUE_FIELD_NUMBER: builtins.int
    BOOL_VALUE_FIELD_NUMBER: builtins.int
    FLOAT_ARRAY_FIELD_NUMBER: builtins.int
    INT_ARRAY_FIELD_NUMBER: builtins.int
    BOOL_ARRAY_FIELD_NUMBER: builtins.int
    STRING_VALUE_FIELD_NUMBER: builtins.int
    RAW_DATA_FIELD_NUMBER: builtins.int
    float_value: builtins.float
    """单个数值（最常见）"""
    int_value: builtins.int
    bool_value: builtins.bool
    string_value: builtins.str
    """字符串类型（用于离散动作）"""
    raw_data: builtins.bytes
    """原始字节数据（用于复杂自定义类型）"""
    @property
    def float_array(self) -> Global___FloatArray:
        """数组类型"""

    @property
    def int_array(self) -> Global___IntArray: ...
    @property
    def bool_array(self) -> Global___BoolArray: ...
    def __init__(
        self,
        *,
        float_value: builtins.float = ...,
        int_value: builtins.int = ...,
        bool_value: builtins.bool = ...,
        float_array: Global___FloatArray | None = ...,
        int_array: Global___IntArray | None = ...,
        bool_array: Global___BoolArray | None = ...,
        string_value: builtins.str = ...,
        raw_data: builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["bool_array", b"bool_array", "bool_value", b"bool_value", "data", b"data", "float_array", b"float_array", "float_value", b"float_value", "int_array", b"int_array", "int_value", b"int_value", "raw_data", b"raw_data", "string_value", b"string_value"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["bool_array", b"bool_array", "bool_value", b"bool_value", "data", b"data", "float_array", b"float_array", "float_value", b"float_value", "int_array", b"int_array", "int_value", b"int_value", "raw_data", b"raw_data", "string_value", b"string_value"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_data: typing_extensions.TypeAlias = typing.Literal["float_value", "int_value", "bool_value", "float_array", "int_array", "bool_array", "string_value", "raw_data"]
    _WhichOneofArgType_data: typing_extensions.TypeAlias = typing.Literal["data", b"data"]
    def WhichOneof(self, oneof_group: _WhichOneofArgType_data) -> _WhichOneofReturnType_data | None: ...

Global___Action: typing_extensions.TypeAlias = Action

@typing.final
class FloatArray(google.protobuf.message.Message):
    """辅助消息类型"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["values", b"values"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FloatArray: typing_extensions.TypeAlias = FloatArray

@typing.final
class IntArray(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["values", b"values"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___IntArray: typing_extensions.TypeAlias = IntArray

@typing.final
class BoolArray(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bool]: ...
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[builtins.bool] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["values", b"values"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BoolArray: typing_extensions.TypeAlias = BoolArray

@typing.final
class GetSpacesRequest(google.protobuf.message.Message):
    """空间定义相关消息"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENV_ID_FIELD_NUMBER: builtins.int
    env_id: builtins.str
    """指定特定env, 由于可以通过config配置设置action space"""
    def __init__(
        self,
        *,
        env_id: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["env_id", b"env_id"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetSpacesRequest: typing_extensions.TypeAlias = GetSpacesRequest

@typing.final
class GetSpacesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACTION_SPACE_FIELD_NUMBER: builtins.int
    OBSERVATION_SPACE_FIELD_NUMBER: builtins.int
    @property
    def action_space(self) -> Global___ActionSpace: ...
    @property
    def observation_space(self) -> Global___ObservationSpace: ...
    def __init__(
        self,
        *,
        action_space: Global___ActionSpace | None = ...,
        observation_space: Global___ObservationSpace | None = ...,
    ) -> None: ...
    _HasFieldArgType: typing_extensions.TypeAlias = typing.Literal["action_space", b"action_space", "observation_space", b"observation_space"]
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["action_space", b"action_space", "observation_space", b"observation_space"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetSpacesResponse: typing_extensions.TypeAlias = GetSpacesResponse

@typing.final
class ActionSpace(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    LOW_FIELD_NUMBER: builtins.int
    HIGH_FIELD_NUMBER: builtins.int
    SHAPE_FIELD_NUMBER: builtins.int
    DTYPE_FIELD_NUMBER: builtins.int
    DISCRETE_VALUES_FIELD_NUMBER: builtins.int
    type: Global___SpaceType.ValueType
    dtype: builtins.str
    """Discrete: [] (标量)
    Box: [action_dim] 
    MultiDiscrete: [num_discrete_groups]
    MultiBinary: [num_binary_actions]
    数据类型: "int32", "float32", etc.
    """
    @property
    def low(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """最小值 (每维度一个值)"""

    @property
    def high(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """最大值 (每维度一个值)"""

    @property
    def shape(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """形状: [action_dimensions]"""

    @property
    def discrete_values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """支持离散浮点值
        当type=DISCRETE时，可选的具体离散值列表
        """

    def __init__(
        self,
        *,
        type: Global___SpaceType.ValueType = ...,
        low: collections.abc.Iterable[builtins.float] | None = ...,
        high: collections.abc.Iterable[builtins.float] | None = ...,
        shape: collections.abc.Iterable[builtins.int] | None = ...,
        dtype: builtins.str = ...,
        discrete_values: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["discrete_values", b"discrete_values", "dtype", b"dtype", "high", b"high", "low", b"low", "shape", b"shape", "type", b"type"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ActionSpace: typing_extensions.TypeAlias = ActionSpace

@typing.final
class ObservationSpace(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    LOW_FIELD_NUMBER: builtins.int
    HIGH_FIELD_NUMBER: builtins.int
    SHAPE_FIELD_NUMBER: builtins.int
    DTYPE_FIELD_NUMBER: builtins.int
    type: Global___SpaceType.ValueType
    dtype: builtins.str
    """数据类型"""
    @property
    def low(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """最小值"""

    @property
    def high(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """最大值"""

    @property
    def shape(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """形状"""

    def __init__(
        self,
        *,
        type: Global___SpaceType.ValueType = ...,
        low: collections.abc.Iterable[builtins.float] | None = ...,
        high: collections.abc.Iterable[builtins.float] | None = ...,
        shape: collections.abc.Iterable[builtins.int] | None = ...,
        dtype: builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: typing_extensions.TypeAlias = typing.Literal["dtype", b"dtype", "high", b"high", "low", b"low", "shape", b"shape", "type", b"type"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ObservationSpace: typing_extensions.TypeAlias = ObservationSpace
