// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/simulation.proto

package simulation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpaceType int32

const (
	SpaceType_BOX      SpaceType = 0 // 连续空间 (gym.spaces.Box) - shape=[dims], 每维有low/high
	SpaceType_DISCRETE SpaceType = 1 // 离散空间 (gym.spaces.Discrete) - shape=[], high=[n-1]表示n个动作
	// 如果discrete_values非空，则动作值来自该列表
	SpaceType_MULTI_DISCRETE SpaceType = 2 // 多离散空间 - shape=[groups], high=[n1-1,n2-1,...]每组动作数
	SpaceType_MULTI_BINARY   SpaceType = 3 // 多二进制空间 - shape=[bits], low/high全为[0]/[1]
	SpaceType_DISCRETE_FLOAT SpaceType = 4 // 离散浮点空间 - 预定义的浮点值列表，使用discrete_values字段
)

// Enum value maps for SpaceType.
var (
	SpaceType_name = map[int32]string{
		0: "BOX",
		1: "DISCRETE",
		2: "MULTI_DISCRETE",
		3: "MULTI_BINARY",
		4: "DISCRETE_FLOAT",
	}
	SpaceType_value = map[string]int32{
		"BOX":            0,
		"DISCRETE":       1,
		"MULTI_DISCRETE": 2,
		"MULTI_BINARY":   3,
		"DISCRETE_FLOAT": 4,
	}
)

func (x SpaceType) Enum() *SpaceType {
	p := new(SpaceType)
	*p = x
	return p
}

func (x SpaceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpaceType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_simulation_proto_enumTypes[0].Descriptor()
}

func (SpaceType) Type() protoreflect.EnumType {
	return &file_proto_simulation_proto_enumTypes[0]
}

func (x SpaceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpaceType.Descriptor instead.
func (SpaceType) EnumDescriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{0}
}

// 基础消息类型
type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_proto_simulation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{0}
}

type GetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenarios     []string               `protobuf:"bytes,1,rep,name=scenarios,proto3" json:"scenarios,omitempty"`
	EnvIds        []string               `protobuf:"bytes,2,rep,name=env_ids,json=envIds,proto3" json:"env_ids,omitempty"`
	Info          *structpb.Struct       `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_proto_simulation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetScenarios() []string {
	if x != nil {
		return x.Scenarios
	}
	return nil
}

func (x *GetInfoResponse) GetEnvIds() []string {
	if x != nil {
		return x.EnvIds
	}
	return nil
}

func (x *GetInfoResponse) GetInfo() *structpb.Struct {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *GetInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateEnvironmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvId         string                 `protobuf:"bytes,1,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	Scenario      string                 `protobuf:"bytes,2,opt,name=scenario,proto3" json:"scenario,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnvironmentRequest) Reset() {
	*x = CreateEnvironmentRequest{}
	mi := &file_proto_simulation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnvironmentRequest) ProtoMessage() {}

func (x *CreateEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*CreateEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEnvironmentRequest) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

func (x *CreateEnvironmentRequest) GetScenario() string {
	if x != nil {
		return x.Scenario
	}
	return ""
}

func (x *CreateEnvironmentRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateEnvironmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnvironmentResponse) Reset() {
	*x = CreateEnvironmentResponse{}
	mi := &file_proto_simulation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnvironmentResponse) ProtoMessage() {}

func (x *CreateEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*CreateEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{3}
}

func (x *CreateEnvironmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateEnvironmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResetEnvironmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvId         string                 `protobuf:"bytes,1,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetEnvironmentRequest) Reset() {
	*x = ResetEnvironmentRequest{}
	mi := &file_proto_simulation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetEnvironmentRequest) ProtoMessage() {}

func (x *ResetEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*ResetEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{4}
}

func (x *ResetEnvironmentRequest) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

type ResetEnvironmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Observations  []*Observation         `protobuf:"bytes,1,rep,name=observations,proto3" json:"observations,omitempty"`
	Info          *structpb.Struct       `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetEnvironmentResponse) Reset() {
	*x = ResetEnvironmentResponse{}
	mi := &file_proto_simulation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetEnvironmentResponse) ProtoMessage() {}

func (x *ResetEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*ResetEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{5}
}

func (x *ResetEnvironmentResponse) GetObservations() []*Observation {
	if x != nil {
		return x.Observations
	}
	return nil
}

func (x *ResetEnvironmentResponse) GetInfo() *structpb.Struct {
	if x != nil {
		return x.Info
	}
	return nil
}

type StepEnvironmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvId         string                 `protobuf:"bytes,1,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	Actions       []*Action              `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepEnvironmentRequest) Reset() {
	*x = StepEnvironmentRequest{}
	mi := &file_proto_simulation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepEnvironmentRequest) ProtoMessage() {}

func (x *StepEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*StepEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{6}
}

func (x *StepEnvironmentRequest) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

func (x *StepEnvironmentRequest) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type StepEnvironmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Observations  []*Observation         `protobuf:"bytes,1,rep,name=observations,proto3" json:"observations,omitempty"`
	Rewards       []float64              `protobuf:"fixed64,2,rep,packed,name=rewards,proto3" json:"rewards,omitempty"`
	Done          []bool                 `protobuf:"varint,3,rep,packed,name=done,proto3" json:"done,omitempty"`
	Info          *structpb.Struct       `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepEnvironmentResponse) Reset() {
	*x = StepEnvironmentResponse{}
	mi := &file_proto_simulation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepEnvironmentResponse) ProtoMessage() {}

func (x *StepEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*StepEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{7}
}

func (x *StepEnvironmentResponse) GetObservations() []*Observation {
	if x != nil {
		return x.Observations
	}
	return nil
}

func (x *StepEnvironmentResponse) GetRewards() []float64 {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *StepEnvironmentResponse) GetDone() []bool {
	if x != nil {
		return x.Done
	}
	return nil
}

func (x *StepEnvironmentResponse) GetInfo() *structpb.Struct {
	if x != nil {
		return x.Info
	}
	return nil
}

type CloseEnvironmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvId         string                 `protobuf:"bytes,1,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseEnvironmentRequest) Reset() {
	*x = CloseEnvironmentRequest{}
	mi := &file_proto_simulation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseEnvironmentRequest) ProtoMessage() {}

func (x *CloseEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*CloseEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{8}
}

func (x *CloseEnvironmentRequest) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

type CloseEnvironmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseEnvironmentResponse) Reset() {
	*x = CloseEnvironmentResponse{}
	mi := &file_proto_simulation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseEnvironmentResponse) ProtoMessage() {}

func (x *CloseEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*CloseEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{9}
}

func (x *CloseEnvironmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CloseEnvironmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 数据类型定义
type Observation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []float64              `protobuf:"fixed64,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observation) Reset() {
	*x = Observation{}
	mi := &file_proto_simulation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observation) ProtoMessage() {}

func (x *Observation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observation.ProtoReflect.Descriptor instead.
func (*Observation) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{10}
}

func (x *Observation) GetData() []float64 {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Observation) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Action struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 通用的action数据，支持多种类型
	//
	// Types that are valid to be assigned to Data:
	//
	//	*Action_FloatValue
	//	*Action_IntValue
	//	*Action_BoolValue
	//	*Action_FloatArray
	//	*Action_IntArray
	//	*Action_BoolArray
	//	*Action_StringValue
	//	*Action_RawData
	Data          isAction_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_proto_simulation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{11}
}

func (x *Action) GetData() isAction_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Action) GetFloatValue() float64 {
	if x != nil {
		if x, ok := x.Data.(*Action_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *Action) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Data.(*Action_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Action) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Data.(*Action_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Action) GetFloatArray() *FloatArray {
	if x != nil {
		if x, ok := x.Data.(*Action_FloatArray); ok {
			return x.FloatArray
		}
	}
	return nil
}

func (x *Action) GetIntArray() *IntArray {
	if x != nil {
		if x, ok := x.Data.(*Action_IntArray); ok {
			return x.IntArray
		}
	}
	return nil
}

func (x *Action) GetBoolArray() *BoolArray {
	if x != nil {
		if x, ok := x.Data.(*Action_BoolArray); ok {
			return x.BoolArray
		}
	}
	return nil
}

func (x *Action) GetStringValue() string {
	if x != nil {
		if x, ok := x.Data.(*Action_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Action) GetRawData() []byte {
	if x != nil {
		if x, ok := x.Data.(*Action_RawData); ok {
			return x.RawData
		}
	}
	return nil
}

type isAction_Data interface {
	isAction_Data()
}

type Action_FloatValue struct {
	// 单个数值（最常见）
	FloatValue float64 `protobuf:"fixed64,1,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type Action_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Action_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Action_FloatArray struct {
	// 数组类型
	FloatArray *FloatArray `protobuf:"bytes,4,opt,name=float_array,json=floatArray,proto3,oneof"`
}

type Action_IntArray struct {
	IntArray *IntArray `protobuf:"bytes,5,opt,name=int_array,json=intArray,proto3,oneof"`
}

type Action_BoolArray struct {
	BoolArray *BoolArray `protobuf:"bytes,6,opt,name=bool_array,json=boolArray,proto3,oneof"`
}

type Action_StringValue struct {
	// 字符串类型（用于离散动作）
	StringValue string `protobuf:"bytes,7,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Action_RawData struct {
	// 原始字节数据（用于复杂自定义类型）
	RawData []byte `protobuf:"bytes,8,opt,name=raw_data,json=rawData,proto3,oneof"`
}

func (*Action_FloatValue) isAction_Data() {}

func (*Action_IntValue) isAction_Data() {}

func (*Action_BoolValue) isAction_Data() {}

func (*Action_FloatArray) isAction_Data() {}

func (*Action_IntArray) isAction_Data() {}

func (*Action_BoolArray) isAction_Data() {}

func (*Action_StringValue) isAction_Data() {}

func (*Action_RawData) isAction_Data() {}

// 辅助消息类型
type FloatArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatArray) Reset() {
	*x = FloatArray{}
	mi := &file_proto_simulation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatArray) ProtoMessage() {}

func (x *FloatArray) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatArray.ProtoReflect.Descriptor instead.
func (*FloatArray) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{12}
}

func (x *FloatArray) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type IntArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []int64                `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntArray) Reset() {
	*x = IntArray{}
	mi := &file_proto_simulation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntArray) ProtoMessage() {}

func (x *IntArray) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntArray.ProtoReflect.Descriptor instead.
func (*IntArray) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{13}
}

func (x *IntArray) GetValues() []int64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type BoolArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []bool                 `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolArray) Reset() {
	*x = BoolArray{}
	mi := &file_proto_simulation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolArray) ProtoMessage() {}

func (x *BoolArray) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolArray.ProtoReflect.Descriptor instead.
func (*BoolArray) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{14}
}

func (x *BoolArray) GetValues() []bool {
	if x != nil {
		return x.Values
	}
	return nil
}

// 空间定义相关消息
type GetSpacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvId         string                 `protobuf:"bytes,1,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"` // 指定特定env, 由于可以通过config配置设置action space
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpacesRequest) Reset() {
	*x = GetSpacesRequest{}
	mi := &file_proto_simulation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpacesRequest) ProtoMessage() {}

func (x *GetSpacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpacesRequest.ProtoReflect.Descriptor instead.
func (*GetSpacesRequest) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{15}
}

func (x *GetSpacesRequest) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

type GetSpacesResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ActionSpace      *ActionSpace           `protobuf:"bytes,1,opt,name=action_space,json=actionSpace,proto3" json:"action_space,omitempty"`
	ObservationSpace *ObservationSpace      `protobuf:"bytes,2,opt,name=observation_space,json=observationSpace,proto3" json:"observation_space,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetSpacesResponse) Reset() {
	*x = GetSpacesResponse{}
	mi := &file_proto_simulation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpacesResponse) ProtoMessage() {}

func (x *GetSpacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpacesResponse.ProtoReflect.Descriptor instead.
func (*GetSpacesResponse) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{16}
}

func (x *GetSpacesResponse) GetActionSpace() *ActionSpace {
	if x != nil {
		return x.ActionSpace
	}
	return nil
}

func (x *GetSpacesResponse) GetObservationSpace() *ObservationSpace {
	if x != nil {
		return x.ObservationSpace
	}
	return nil
}

type ActionSpace struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  SpaceType              `protobuf:"varint,1,opt,name=type,proto3,enum=simulation.SpaceType" json:"type,omitempty"`
	Low   []float64              `protobuf:"fixed64,2,rep,packed,name=low,proto3" json:"low,omitempty"`    // 最小值 (每维度一个值)
	High  []float64              `protobuf:"fixed64,3,rep,packed,name=high,proto3" json:"high,omitempty"`  // 最大值 (每维度一个值)
	Shape []int32                `protobuf:"varint,4,rep,packed,name=shape,proto3" json:"shape,omitempty"` // 形状: [action_dimensions]
	// Discrete: [] (标量)
	// Box: [action_dim]
	// MultiDiscrete: [num_discrete_groups]
	// MultiBinary: [num_binary_actions]
	Dtype string `protobuf:"bytes,5,opt,name=dtype,proto3" json:"dtype,omitempty"` // 数据类型: "int32", "float32", etc.
	// 支持离散浮点值
	DiscreteValues []float64 `protobuf:"fixed64,6,rep,packed,name=discrete_values,json=discreteValues,proto3" json:"discrete_values,omitempty"` // 当type=DISCRETE时，可选的具体离散值列表
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActionSpace) Reset() {
	*x = ActionSpace{}
	mi := &file_proto_simulation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionSpace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSpace) ProtoMessage() {}

func (x *ActionSpace) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSpace.ProtoReflect.Descriptor instead.
func (*ActionSpace) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{17}
}

func (x *ActionSpace) GetType() SpaceType {
	if x != nil {
		return x.Type
	}
	return SpaceType_BOX
}

func (x *ActionSpace) GetLow() []float64 {
	if x != nil {
		return x.Low
	}
	return nil
}

func (x *ActionSpace) GetHigh() []float64 {
	if x != nil {
		return x.High
	}
	return nil
}

func (x *ActionSpace) GetShape() []int32 {
	if x != nil {
		return x.Shape
	}
	return nil
}

func (x *ActionSpace) GetDtype() string {
	if x != nil {
		return x.Dtype
	}
	return ""
}

func (x *ActionSpace) GetDiscreteValues() []float64 {
	if x != nil {
		return x.DiscreteValues
	}
	return nil
}

type ObservationSpace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          SpaceType              `protobuf:"varint,1,opt,name=type,proto3,enum=simulation.SpaceType" json:"type,omitempty"`
	Low           []float64              `protobuf:"fixed64,2,rep,packed,name=low,proto3" json:"low,omitempty"`    // 最小值
	High          []float64              `protobuf:"fixed64,3,rep,packed,name=high,proto3" json:"high,omitempty"`  // 最大值
	Shape         []int32                `protobuf:"varint,4,rep,packed,name=shape,proto3" json:"shape,omitempty"` // 形状
	Dtype         string                 `protobuf:"bytes,5,opt,name=dtype,proto3" json:"dtype,omitempty"`         // 数据类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObservationSpace) Reset() {
	*x = ObservationSpace{}
	mi := &file_proto_simulation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservationSpace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservationSpace) ProtoMessage() {}

func (x *ObservationSpace) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservationSpace.ProtoReflect.Descriptor instead.
func (*ObservationSpace) Descriptor() ([]byte, []int) {
	return file_proto_simulation_proto_rawDescGZIP(), []int{18}
}

func (x *ObservationSpace) GetType() SpaceType {
	if x != nil {
		return x.Type
	}
	return SpaceType_BOX
}

func (x *ObservationSpace) GetLow() []float64 {
	if x != nil {
		return x.Low
	}
	return nil
}

func (x *ObservationSpace) GetHigh() []float64 {
	if x != nil {
		return x.High
	}
	return nil
}

func (x *ObservationSpace) GetShape() []int32 {
	if x != nil {
		return x.Shape
	}
	return nil
}

func (x *ObservationSpace) GetDtype() string {
	if x != nil {
		return x.Dtype
	}
	return ""
}

var File_proto_simulation_proto protoreflect.FileDescriptor

const file_proto_simulation_proto_rawDesc = "" +
	"\n" +
	"\x16proto/simulation.proto\x12\n" +
	"simulation\x1a\x1cgoogle/protobuf/struct.proto\"\x10\n" +
	"\x0eGetInfoRequest\"\xa3\x01\n" +
	"\x0fGetInfoResponse\x12\x1c\n" +
	"\tscenarios\x18\x01 \x03(\tR\tscenarios\x12\x17\n" +
	"\aenv_ids\x18\x02 \x03(\tR\x06envIds\x12+\n" +
	"\x04info\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04info\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"~\n" +
	"\x18CreateEnvironmentRequest\x12\x15\n" +
	"\x06env_id\x18\x01 \x01(\tR\x05envId\x12\x1a\n" +
	"\bscenario\x18\x02 \x01(\tR\bscenario\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06config\"O\n" +
	"\x19CreateEnvironmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\x17ResetEnvironmentRequest\x12\x15\n" +
	"\x06env_id\x18\x01 \x01(\tR\x05envId\"\x84\x01\n" +
	"\x18ResetEnvironmentResponse\x12;\n" +
	"\fobservations\x18\x01 \x03(\v2\x17.simulation.ObservationR\fobservations\x12+\n" +
	"\x04info\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04info\"]\n" +
	"\x16StepEnvironmentRequest\x12\x15\n" +
	"\x06env_id\x18\x01 \x01(\tR\x05envId\x12,\n" +
	"\aactions\x18\x02 \x03(\v2\x12.simulation.ActionR\aactions\"\xb1\x01\n" +
	"\x17StepEnvironmentResponse\x12;\n" +
	"\fobservations\x18\x01 \x03(\v2\x17.simulation.ObservationR\fobservations\x12\x18\n" +
	"\arewards\x18\x02 \x03(\x01R\arewards\x12\x12\n" +
	"\x04done\x18\x03 \x03(\bR\x04done\x12+\n" +
	"\x04info\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04info\"0\n" +
	"\x17CloseEnvironmentRequest\x12\x15\n" +
	"\x06env_id\x18\x01 \x01(\tR\x05envId\"N\n" +
	"\x18CloseEnvironmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"V\n" +
	"\vObservation\x12\x12\n" +
	"\x04data\x18\x01 \x03(\x01R\x04data\x123\n" +
	"\bmetadata\x18\x02 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xdd\x02\n" +
	"\x06Action\x12!\n" +
	"\vfloat_value\x18\x01 \x01(\x01H\x00R\n" +
	"floatValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x03 \x01(\bH\x00R\tboolValue\x129\n" +
	"\vfloat_array\x18\x04 \x01(\v2\x16.simulation.FloatArrayH\x00R\n" +
	"floatArray\x123\n" +
	"\tint_array\x18\x05 \x01(\v2\x14.simulation.IntArrayH\x00R\bintArray\x126\n" +
	"\n" +
	"bool_array\x18\x06 \x01(\v2\x15.simulation.BoolArrayH\x00R\tboolArray\x12#\n" +
	"\fstring_value\x18\a \x01(\tH\x00R\vstringValue\x12\x1b\n" +
	"\braw_data\x18\b \x01(\fH\x00R\arawDataB\x06\n" +
	"\x04data\"$\n" +
	"\n" +
	"FloatArray\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06values\"\"\n" +
	"\bIntArray\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x03R\x06values\"#\n" +
	"\tBoolArray\x12\x16\n" +
	"\x06values\x18\x01 \x03(\bR\x06values\")\n" +
	"\x10GetSpacesRequest\x12\x15\n" +
	"\x06env_id\x18\x01 \x01(\tR\x05envId\"\x9a\x01\n" +
	"\x11GetSpacesResponse\x12:\n" +
	"\faction_space\x18\x01 \x01(\v2\x17.simulation.ActionSpaceR\vactionSpace\x12I\n" +
	"\x11observation_space\x18\x02 \x01(\v2\x1c.simulation.ObservationSpaceR\x10observationSpace\"\xb3\x01\n" +
	"\vActionSpace\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.simulation.SpaceTypeR\x04type\x12\x10\n" +
	"\x03low\x18\x02 \x03(\x01R\x03low\x12\x12\n" +
	"\x04high\x18\x03 \x03(\x01R\x04high\x12\x14\n" +
	"\x05shape\x18\x04 \x03(\x05R\x05shape\x12\x14\n" +
	"\x05dtype\x18\x05 \x01(\tR\x05dtype\x12'\n" +
	"\x0fdiscrete_values\x18\x06 \x03(\x01R\x0ediscreteValues\"\x8f\x01\n" +
	"\x10ObservationSpace\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.simulation.SpaceTypeR\x04type\x12\x10\n" +
	"\x03low\x18\x02 \x03(\x01R\x03low\x12\x12\n" +
	"\x04high\x18\x03 \x03(\x01R\x04high\x12\x14\n" +
	"\x05shape\x18\x04 \x03(\x05R\x05shape\x12\x14\n" +
	"\x05dtype\x18\x05 \x01(\tR\x05dtype*\\\n" +
	"\tSpaceType\x12\a\n" +
	"\x03BOX\x10\x00\x12\f\n" +
	"\bDISCRETE\x10\x01\x12\x12\n" +
	"\x0eMULTI_DISCRETE\x10\x02\x12\x10\n" +
	"\fMULTI_BINARY\x10\x03\x12\x12\n" +
	"\x0eDISCRETE_FLOAT\x10\x042\xf8\x04\n" +
	"\x11SimulationService\x12B\n" +
	"\aGetInfo\x12\x1a.simulation.GetInfoRequest\x1a\x1b.simulation.GetInfoResponse\x12`\n" +
	"\x11CreateEnvironment\x12$.simulation.CreateEnvironmentRequest\x1a%.simulation.CreateEnvironmentResponse\x12]\n" +
	"\x10ResetEnvironment\x12#.simulation.ResetEnvironmentRequest\x1a$.simulation.ResetEnvironmentResponse\x12Z\n" +
	"\x0fStepEnvironment\x12\".simulation.StepEnvironmentRequest\x1a#.simulation.StepEnvironmentResponse\x12]\n" +
	"\x10CloseEnvironment\x12#.simulation.CloseEnvironmentRequest\x1a$.simulation.CloseEnvironmentResponse\x12H\n" +
	"\tGetSpaces\x12\x1c.simulation.GetSpacesRequest\x1a\x1d.simulation.GetSpacesResponse\x12Y\n" +
	"\n" +
	"StreamStep\x12\".simulation.StepEnvironmentRequest\x1a#.simulation.StepEnvironmentResponse(\x010\x01B2Z0github.com/jelech/rl_env_engine/proto/simulationb\x06proto3"

var (
	file_proto_simulation_proto_rawDescOnce sync.Once
	file_proto_simulation_proto_rawDescData []byte
)

func file_proto_simulation_proto_rawDescGZIP() []byte {
	file_proto_simulation_proto_rawDescOnce.Do(func() {
		file_proto_simulation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_simulation_proto_rawDesc), len(file_proto_simulation_proto_rawDesc)))
	})
	return file_proto_simulation_proto_rawDescData
}

var file_proto_simulation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_simulation_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_simulation_proto_goTypes = []any{
	(SpaceType)(0),                    // 0: simulation.SpaceType
	(*GetInfoRequest)(nil),            // 1: simulation.GetInfoRequest
	(*GetInfoResponse)(nil),           // 2: simulation.GetInfoResponse
	(*CreateEnvironmentRequest)(nil),  // 3: simulation.CreateEnvironmentRequest
	(*CreateEnvironmentResponse)(nil), // 4: simulation.CreateEnvironmentResponse
	(*ResetEnvironmentRequest)(nil),   // 5: simulation.ResetEnvironmentRequest
	(*ResetEnvironmentResponse)(nil),  // 6: simulation.ResetEnvironmentResponse
	(*StepEnvironmentRequest)(nil),    // 7: simulation.StepEnvironmentRequest
	(*StepEnvironmentResponse)(nil),   // 8: simulation.StepEnvironmentResponse
	(*CloseEnvironmentRequest)(nil),   // 9: simulation.CloseEnvironmentRequest
	(*CloseEnvironmentResponse)(nil),  // 10: simulation.CloseEnvironmentResponse
	(*Observation)(nil),               // 11: simulation.Observation
	(*Action)(nil),                    // 12: simulation.Action
	(*FloatArray)(nil),                // 13: simulation.FloatArray
	(*IntArray)(nil),                  // 14: simulation.IntArray
	(*BoolArray)(nil),                 // 15: simulation.BoolArray
	(*GetSpacesRequest)(nil),          // 16: simulation.GetSpacesRequest
	(*GetSpacesResponse)(nil),         // 17: simulation.GetSpacesResponse
	(*ActionSpace)(nil),               // 18: simulation.ActionSpace
	(*ObservationSpace)(nil),          // 19: simulation.ObservationSpace
	(*structpb.Struct)(nil),           // 20: google.protobuf.Struct
}
var file_proto_simulation_proto_depIdxs = []int32{
	20, // 0: simulation.GetInfoResponse.info:type_name -> google.protobuf.Struct
	20, // 1: simulation.CreateEnvironmentRequest.config:type_name -> google.protobuf.Struct
	11, // 2: simulation.ResetEnvironmentResponse.observations:type_name -> simulation.Observation
	20, // 3: simulation.ResetEnvironmentResponse.info:type_name -> google.protobuf.Struct
	12, // 4: simulation.StepEnvironmentRequest.actions:type_name -> simulation.Action
	11, // 5: simulation.StepEnvironmentResponse.observations:type_name -> simulation.Observation
	20, // 6: simulation.StepEnvironmentResponse.info:type_name -> google.protobuf.Struct
	20, // 7: simulation.Observation.metadata:type_name -> google.protobuf.Struct
	13, // 8: simulation.Action.float_array:type_name -> simulation.FloatArray
	14, // 9: simulation.Action.int_array:type_name -> simulation.IntArray
	15, // 10: simulation.Action.bool_array:type_name -> simulation.BoolArray
	18, // 11: simulation.GetSpacesResponse.action_space:type_name -> simulation.ActionSpace
	19, // 12: simulation.GetSpacesResponse.observation_space:type_name -> simulation.ObservationSpace
	0,  // 13: simulation.ActionSpace.type:type_name -> simulation.SpaceType
	0,  // 14: simulation.ObservationSpace.type:type_name -> simulation.SpaceType
	1,  // 15: simulation.SimulationService.GetInfo:input_type -> simulation.GetInfoRequest
	3,  // 16: simulation.SimulationService.CreateEnvironment:input_type -> simulation.CreateEnvironmentRequest
	5,  // 17: simulation.SimulationService.ResetEnvironment:input_type -> simulation.ResetEnvironmentRequest
	7,  // 18: simulation.SimulationService.StepEnvironment:input_type -> simulation.StepEnvironmentRequest
	9,  // 19: simulation.SimulationService.CloseEnvironment:input_type -> simulation.CloseEnvironmentRequest
	16, // 20: simulation.SimulationService.GetSpaces:input_type -> simulation.GetSpacesRequest
	7,  // 21: simulation.SimulationService.StreamStep:input_type -> simulation.StepEnvironmentRequest
	2,  // 22: simulation.SimulationService.GetInfo:output_type -> simulation.GetInfoResponse
	4,  // 23: simulation.SimulationService.CreateEnvironment:output_type -> simulation.CreateEnvironmentResponse
	6,  // 24: simulation.SimulationService.ResetEnvironment:output_type -> simulation.ResetEnvironmentResponse
	8,  // 25: simulation.SimulationService.StepEnvironment:output_type -> simulation.StepEnvironmentResponse
	10, // 26: simulation.SimulationService.CloseEnvironment:output_type -> simulation.CloseEnvironmentResponse
	17, // 27: simulation.SimulationService.GetSpaces:output_type -> simulation.GetSpacesResponse
	8,  // 28: simulation.SimulationService.StreamStep:output_type -> simulation.StepEnvironmentResponse
	22, // [22:29] is the sub-list for method output_type
	15, // [15:22] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_simulation_proto_init() }
func file_proto_simulation_proto_init() {
	if File_proto_simulation_proto != nil {
		return
	}
	file_proto_simulation_proto_msgTypes[11].OneofWrappers = []any{
		(*Action_FloatValue)(nil),
		(*Action_IntValue)(nil),
		(*Action_BoolValue)(nil),
		(*Action_FloatArray)(nil),
		(*Action_IntArray)(nil),
		(*Action_BoolArray)(nil),
		(*Action_StringValue)(nil),
		(*Action_RawData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_simulation_proto_rawDesc), len(file_proto_simulation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_simulation_proto_goTypes,
		DependencyIndexes: file_proto_simulation_proto_depIdxs,
		EnumInfos:         file_proto_simulation_proto_enumTypes,
		MessageInfos:      file_proto_simulation_proto_msgTypes,
	}.Build()
	File_proto_simulation_proto = out.File
	file_proto_simulation_proto_goTypes = nil
	file_proto_simulation_proto_depIdxs = nil
}
