// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: proto/simulation.proto

package simulation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SimulationService_GetInfo_FullMethodName           = "/simulation.SimulationService/GetInfo"
	SimulationService_CreateEnvironment_FullMethodName = "/simulation.SimulationService/CreateEnvironment"
	SimulationService_ResetEnvironment_FullMethodName  = "/simulation.SimulationService/ResetEnvironment"
	SimulationService_StepEnvironment_FullMethodName   = "/simulation.SimulationService/StepEnvironment"
	SimulationService_CloseEnvironment_FullMethodName  = "/simulation.SimulationService/CloseEnvironment"
	SimulationService_GetSpaces_FullMethodName         = "/simulation.SimulationService/GetSpaces"
	SimulationService_StreamStep_FullMethodName        = "/simulation.SimulationService/StreamStep"
)

// SimulationServiceClient is the client API for SimulationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SimulationService 定义仿真服务的gRPC接口
type SimulationServiceClient interface {
	// GetInfo 获取服务信息
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	// CreateEnvironment 创建环境
	CreateEnvironment(ctx context.Context, in *CreateEnvironmentRequest, opts ...grpc.CallOption) (*CreateEnvironmentResponse, error)
	// ResetEnvironment 重置环境
	ResetEnvironment(ctx context.Context, in *ResetEnvironmentRequest, opts ...grpc.CallOption) (*ResetEnvironmentResponse, error)
	// StepEnvironment 执行一步仿真
	StepEnvironment(ctx context.Context, in *StepEnvironmentRequest, opts ...grpc.CallOption) (*StepEnvironmentResponse, error)
	// CloseEnvironment 关闭环境
	CloseEnvironment(ctx context.Context, in *CloseEnvironmentRequest, opts ...grpc.CallOption) (*CloseEnvironmentResponse, error)
	// GetSpaces 获取环境的动作空间和观察空间定义
	GetSpaces(ctx context.Context, in *GetSpacesRequest, opts ...grpc.CallOption) (*GetSpacesResponse, error)
	// StreamStep 流式执行仿真步骤 (可选，用于实时仿真)
	StreamStep(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StepEnvironmentRequest, StepEnvironmentResponse], error)
}

type simulationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSimulationServiceClient(cc grpc.ClientConnInterface) SimulationServiceClient {
	return &simulationServiceClient{cc}
}

func (c *simulationServiceClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, SimulationService_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) CreateEnvironment(ctx context.Context, in *CreateEnvironmentRequest, opts ...grpc.CallOption) (*CreateEnvironmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEnvironmentResponse)
	err := c.cc.Invoke(ctx, SimulationService_CreateEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) ResetEnvironment(ctx context.Context, in *ResetEnvironmentRequest, opts ...grpc.CallOption) (*ResetEnvironmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetEnvironmentResponse)
	err := c.cc.Invoke(ctx, SimulationService_ResetEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) StepEnvironment(ctx context.Context, in *StepEnvironmentRequest, opts ...grpc.CallOption) (*StepEnvironmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StepEnvironmentResponse)
	err := c.cc.Invoke(ctx, SimulationService_StepEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) CloseEnvironment(ctx context.Context, in *CloseEnvironmentRequest, opts ...grpc.CallOption) (*CloseEnvironmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseEnvironmentResponse)
	err := c.cc.Invoke(ctx, SimulationService_CloseEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) GetSpaces(ctx context.Context, in *GetSpacesRequest, opts ...grpc.CallOption) (*GetSpacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSpacesResponse)
	err := c.cc.Invoke(ctx, SimulationService_GetSpaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulationServiceClient) StreamStep(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StepEnvironmentRequest, StepEnvironmentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SimulationService_ServiceDesc.Streams[0], SimulationService_StreamStep_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StepEnvironmentRequest, StepEnvironmentResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SimulationService_StreamStepClient = grpc.BidiStreamingClient[StepEnvironmentRequest, StepEnvironmentResponse]

// SimulationServiceServer is the server API for SimulationService service.
// All implementations must embed UnimplementedSimulationServiceServer
// for forward compatibility.
//
// SimulationService 定义仿真服务的gRPC接口
type SimulationServiceServer interface {
	// GetInfo 获取服务信息
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	// CreateEnvironment 创建环境
	CreateEnvironment(context.Context, *CreateEnvironmentRequest) (*CreateEnvironmentResponse, error)
	// ResetEnvironment 重置环境
	ResetEnvironment(context.Context, *ResetEnvironmentRequest) (*ResetEnvironmentResponse, error)
	// StepEnvironment 执行一步仿真
	StepEnvironment(context.Context, *StepEnvironmentRequest) (*StepEnvironmentResponse, error)
	// CloseEnvironment 关闭环境
	CloseEnvironment(context.Context, *CloseEnvironmentRequest) (*CloseEnvironmentResponse, error)
	// GetSpaces 获取环境的动作空间和观察空间定义
	GetSpaces(context.Context, *GetSpacesRequest) (*GetSpacesResponse, error)
	// StreamStep 流式执行仿真步骤 (可选，用于实时仿真)
	StreamStep(grpc.BidiStreamingServer[StepEnvironmentRequest, StepEnvironmentResponse]) error
	mustEmbedUnimplementedSimulationServiceServer()
}

// UnimplementedSimulationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSimulationServiceServer struct{}

func (UnimplementedSimulationServiceServer) GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedSimulationServiceServer) CreateEnvironment(context.Context, *CreateEnvironmentRequest) (*CreateEnvironmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEnvironment not implemented")
}
func (UnimplementedSimulationServiceServer) ResetEnvironment(context.Context, *ResetEnvironmentRequest) (*ResetEnvironmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetEnvironment not implemented")
}
func (UnimplementedSimulationServiceServer) StepEnvironment(context.Context, *StepEnvironmentRequest) (*StepEnvironmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StepEnvironment not implemented")
}
func (UnimplementedSimulationServiceServer) CloseEnvironment(context.Context, *CloseEnvironmentRequest) (*CloseEnvironmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseEnvironment not implemented")
}
func (UnimplementedSimulationServiceServer) GetSpaces(context.Context, *GetSpacesRequest) (*GetSpacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSpaces not implemented")
}
func (UnimplementedSimulationServiceServer) StreamStep(grpc.BidiStreamingServer[StepEnvironmentRequest, StepEnvironmentResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamStep not implemented")
}
func (UnimplementedSimulationServiceServer) mustEmbedUnimplementedSimulationServiceServer() {}
func (UnimplementedSimulationServiceServer) testEmbeddedByValue()                           {}

// UnsafeSimulationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimulationServiceServer will
// result in compilation errors.
type UnsafeSimulationServiceServer interface {
	mustEmbedUnimplementedSimulationServiceServer()
}

func RegisterSimulationServiceServer(s grpc.ServiceRegistrar, srv SimulationServiceServer) {
	// If the following call panics, it indicates UnimplementedSimulationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SimulationService_ServiceDesc, srv)
}

func _SimulationService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_CreateEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).CreateEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_CreateEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).CreateEnvironment(ctx, req.(*CreateEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_ResetEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).ResetEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_ResetEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).ResetEnvironment(ctx, req.(*ResetEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_StepEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).StepEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_StepEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).StepEnvironment(ctx, req.(*StepEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_CloseEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).CloseEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_CloseEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).CloseEnvironment(ctx, req.(*CloseEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_GetSpaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulationServiceServer).GetSpaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulationService_GetSpaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulationServiceServer).GetSpaces(ctx, req.(*GetSpacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulationService_StreamStep_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SimulationServiceServer).StreamStep(&grpc.GenericServerStream[StepEnvironmentRequest, StepEnvironmentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SimulationService_StreamStepServer = grpc.BidiStreamingServer[StepEnvironmentRequest, StepEnvironmentResponse]

// SimulationService_ServiceDesc is the grpc.ServiceDesc for SimulationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimulationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "simulation.SimulationService",
	HandlerType: (*SimulationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _SimulationService_GetInfo_Handler,
		},
		{
			MethodName: "CreateEnvironment",
			Handler:    _SimulationService_CreateEnvironment_Handler,
		},
		{
			MethodName: "ResetEnvironment",
			Handler:    _SimulationService_ResetEnvironment_Handler,
		},
		{
			MethodName: "StepEnvironment",
			Handler:    _SimulationService_StepEnvironment_Handler,
		},
		{
			MethodName: "CloseEnvironment",
			Handler:    _SimulationService_CloseEnvironment_Handler,
		},
		{
			MethodName: "GetSpaces",
			Handler:    _SimulationService_GetSpaces_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamStep",
			Handler:       _SimulationService_StreamStep_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/simulation.proto",
}
